module.exports = {
    inputs: {
        orderId: "G3Y2D9VN3L",
        userAddress1: "Kalidindi Towers",
        userAddress2: "Kalidindi Towers, Kiladi Vari St, Tuni, Andhra Pradesh 533401, India, Tuni",
        userAddress3: "533401, Ph: 9398084775",
        orderDate: "21/05/2025",
        deliveryPlace: "Tuni",
        invoiceNumber: "ST5ZY-77459",
        invoiceDate: "21/05/2025",
        checkoutDoc: {
            _id: {
                buffer: new Uint8Array([104, 45, 158, 104, 253, 68, 79, 188, 46, 7, 195, 145]),
            },
            products: [
                {
                    id: 4883,
                    name: "Local Bougainvillea Plant(Large)",
                    description: "<p>Native to South America, Bougainvillea thrives in hot, sunny climates and is drought-tolerant once established. It prefers well-drained sandy or loamy soil and requires minimal watering, avoiding overwatering to prevent root rot. Prune regularly to control its size and shape while encouraging more blooms. With our Flitzy services, you can maintain it hassle-free.</p>\n",
                    price: 990,
                    regular_price: 900,
                    sale_price: 1440,
                    manage_stock: true,
                    stock_quantity: 46,
                    rating_count: 0,
                    image: "https://flitzy.in/wp-content/uploads/2025/04/flitzy-images2FLocalBougainvilleaPlantLarg-3-1-1-1-1-1-1.jpeg",
                    category: [
                        "Sri Venkateshwara nursery ",
                    ],
                    subCategory: "Products",
                    nursery: 630,
                    nurseryCode: "NURS719265rg368flm8t73yqi",
                    quantity: 1,
                },
            ],
            walletAmount: 163.56,
            cartPrice: 1626.61,
            flitzyPrice: 90,
            gstPrice: 187.11,
            transactionFee: 49.5,
            vendorPrice: 1300,
            transportPrice: 400,
            user_id: "4209532jlma51xpkp",
            store_id: 630,
            merchantTransactionId: "3c27cu5cqbmaxqzc6h",
            transactionId: "3c27cu5cqbmaxqzc6i",
            status: "ORDER_INITIATED",
            status_reason: "ORDER_INITIATED",
            isScheduled: false,
            promocodeApplied: false,
            store_name: "Sri Venkateshwara nursery ",
            isTransactionSuccessful: false,
            orderId: "G3Y2D9VN3L",
            slot: "13-16",
            slotLabel: "1pm - 4pm",
            vendorPaymentStatus: "PAYMENT_PENDING",
            updated_date: null,
            created_date: "2025-05-21T09:35:36.094Z",
            created_date_epoch: 1747820136094,
            invoiceDownloadUrl: "https://firebasestorage.googleapis.com/v0/b/flitzy-india-pvt-ltd.firebasestorage.app/o/daily_reports%2ForderInvoice1_G3Y2D9VN3L.pdf?alt=media",
        },
    },
    inputs_1: {
        orderId: "SVYFUT5OX6",
        userAddress1: "Kalidindi Towers",
        userAddress2: "Kalidindi Towers, Kiladi Vari St, Tuni, Andhra Pradesh 533401, India, Tuni",
        userAddress3: "533401, Ph: 9398084775",
        orderDate: "21/05/2025",
        deliveryPlace: "Tuni",
        invoiceNumber: "BM817-58891",
        invoiceDate: "21/05/2025",
        checkoutDoc: {
            _id: {
                buffer: new Uint8Array([104, 45, 185, 170, 146, 133, 36, 54, 197, 237, 158, 78]),
            },
            products: [
                {
                    id: 4883,
                    name: "Local Bougainvillea Plant(Large)",
                    description: "<p>Native to South America, Bougainvillea thrives in hot, sunny climates and is drought-tolerant once established. It prefers well-drained sandy or loamy soil and requires minimal watering, avoiding overwatering to prevent root rot. Prune regularly to control its size and shape while encouraging more blooms. With our Flitzy services, you can maintain it hassle-free.</p>\n",
                    price: 990,
                    regular_price: 900,
                    sale_price: 1440,
                    manage_stock: true,
                    stock_quantity: 46,
                    rating_count: 0,
                    image: "https://flitzy.in/wp-content/uploads/2025/04/flitzy-images2FLocalBougainvilleaPlantLarg-3-1-1-1-1-1-1.jpeg",
                    category: [
                        "Sri Venkateshwara nursery ",
                    ],
                    subCategory: "Products",
                    nursery: 630,
                    nurseryCode: "NURS719265rg368flm8t73yqi",
                    quantity: 5,
                },
            ],
            walletAmount: 163.56,
            cartPrice: 6533.05,
            flitzyPrice: 450,
            gstPrice: 935.55,
            transactionFee: 247.5,
            vendorPrice: 4900,
            transportPrice: 400,
            user_id: "4209532jlma51xpkp",
            store_id: 630,
            merchantTransactionId: "3c27cu5ku8maxv4wh9",
            transactionId: "3c27cu5ku8maxv4wha",
            status: "ORDER_INITIATED",
            status_reason: "ORDER_INITIATED",
            isScheduled: false,
            promocodeApplied: false,
            store_name: "Sri Venkateshwara nursery ",
            isTransactionSuccessful: false,
            orderId: "SVYFUT5OX6",
            slot: "13-16",
            slotLabel: "1pm - 4pm",
            vendorPaymentStatus: "PAYMENT_PENDING",
            updated_date: null,
            created_date: "2025-05-21T11:31:54.139Z",
            created_date_epoch: 1747827114139,
            invoiceDownloadUrl: "https://firebasestorage.googleapis.com/v0/b/flitzy-india-pvt-ltd.firebasestorage.app/o/daily_reports%2ForderInvoice1_SVYFUT5OX6.pdf?alt=media",
            isOrderEdited: true,
        },
        modifiedDoc: {
            addToWallet: true,
            amount: 3679.84,
            cartPrice: 6533.05,
            created_date: "2025-05-21T11:31:54.139Z",
            flitzyPrice: 450,
            gstPrice: 935.55,
            merchantTransactionId: "3c27cu5ku8maxv6tf5",
            noUpdate: false,
            payExtraAmount: false,
            products: [
                {
                    id: 4883,
                    name: "Local Bougainvillea Plant(Large)",
                    description: "<p>Native to South America, Bougainvillea thrives in hot, sunny climates and is drought-tolerant once established. It prefers well-drained sandy or loamy soil and requires minimal watering, avoiding overwatering to prevent root rot. Prune regularly to control its size and shape while encouraging more blooms. With our Flitzy services, you can maintain it hassle-free.</p>\n",
                    price: 990,
                    regular_price: 900,
                    sale_price: 1440,
                    manage_stock: true,
                    stock_quantity: 46,
                    rating_count: 0,
                    image: "https://flitzy.in/wp-content/uploads/2025/04/flitzy-images2FLocalBougainvilleaPlantLarg-3-1-1-1-1-1-1.jpeg",
                    category: [
                        "Sri Venkateshwara nursery ",
                    ],
                    subCategory: "Products",
                    nursery: 630,
                    nurseryCode: "NURS719265rg368flm8t73yqi",
                    quantity: 5,
                },
            ],
            transactionFee: 247.5,
            transportPrice: 400,
            user_id: "4209532jlma51xpkp",
            vendorPrice: 4900,
            walletAmount: 163.56,
        },
    }
};